# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: botanica@interflora.no
brand: Botanica Blosmter
headline: Inventor, Engineer and Futurist
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.botanica.no" # the base hostname & protocol for your site
copyright: 2016 Botanica Blomster AS. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: botanica@interflora.no
phone: 55 31 04 08

# Tracking
googleAnalitycsID: UA-86558255-1

